source 'https://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'sqlite3'
gem 'cucumber'
gem 'database_cleaner'
gem 'capybara'
gem 'selenium-webdriver'
gem 'rspec'
gem 'gherkin'
gem 'poltergeist', '~> 1.11'
gem 'settingslogic'